HelloWorld/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls',namespace='polls')),
    url(r'^admin/', include(admin.site.urls)),
]

polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
        url(r'^$', views.index, name='index'),
        url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
        url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
        url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
            ]

polls/models.py
from django.db import models
import datetime

from django.utils import timezone
# Create your models here.


class Question(models.Model):
        question_text = models.CharField(max_length=200)
        pub_date = models.DateTimeField('date published')
        def __str__(self):
            return self.question_text
        def was_published_recently(self):
            return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
        was_published_recently.admin_order_field = 'pub_date'
        was_published_recently.boolean = True
        was_published_recently.short_description = 'Published recently?'
class Choice(models.Model):
        question = models.ForeignKey(Question)
        choice_text = models.CharField(max_length=200)
        votes = models.IntegerField(default=0)
        def __str__(self):
            return self.choice_text

whatdayisit/models.py
from django.db import models

# Create your models here.

polls/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from .models import Question,Choice

# Create your views here.
def index(request):
    l_q_l= Question.objects.order_by('-pub_date')[:5]
    
    return render(request,'polls/index.html',{'latest_question_list': l_q_l,})


def detail(request,question_id):  
    question = get_object_or_404(Question, pk=question_id) 

    return render(request,'polls/details.html',{'question':question})

def results(request,question_id):  
    return HttpResponse("You are looking at the results of question %s" % question_id)

def vote(request,question_id):  
    
    return HttpResponse("You are voting on question %s" % question_id)

whatdayisit/views.py
from django.shortcuts import render

# Create your views here.

polls/templates/polls/details.html
<table>
    <tr>
        <td>Question text</td>
        <td>Publish date</td>
        <td>Recently published?</td>

    </tr>
    <tr>
        <td>{{question.question_text}}</td>
        <td>{{question.pub_date}}</td>
        {% if question.was_published_recently %}
            <td>Yes</td>
        {% else %}
            <td>No</td>
        {% endif %}
    </tr>

    

</table>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}